#!/bin/sh
[ -n "$IPKG_INSTROOT" ] || {
	# 升级时老配置里没有新选项, 补默认值(引擎本身也有内置默认, 这里只为 LuCI 显示)
	[ -n "$(uci -q get campass.global.switch_timeout)" ] || {
		uci -q set campass.global.switch_timeout='120'
		uci commit campass
	}
	[ -n "$(uci -q get campass.global.watchdog_failover)" ] || {
		uci -q set campass.global.watchdog_failover='1'
		uci commit campass
	}
	# 恢复阈值从"秒"改为"连续探测失败次数": 老配置按 ceil(阈值/探测间隔) 折算,
	# 折算后删掉旧键, 免得配置里留个已经没人读的 watchdog_threshold
	[ -n "$(uci -q get campass.global.watchdog_fails)" ] || {
		old_th="$(uci -q get campass.global.watchdog_threshold)"
		old_iv="$(uci -q get campass.global.watchdog_interval)"
		n=3
		if [ -n "$old_th" ] && [ -n "$old_iv" ] && [ "$old_iv" -gt 0 ] 2>/dev/null; then
			n=$(( (old_th + old_iv - 1) / old_iv ))
			[ "$n" -lt 1 ] && n=1
		fi
		uci -q set campass.global.watchdog_fails="$n"
		uci -q delete campass.global.watchdog_threshold
		uci commit campass
	}
	[ -n "$(uci -q get campass.global.log_max_lines)" ] || {
		uci -q set campass.global.log_max_lines='2000'
		uci commit campass
	}
	[ -n "$(uci -q get campass.global.probe_family)" ] || {
		uci -q set campass.global.probe_family='any'
		uci commit campass
	}
	[ -n "$(uci -q get campass.global.probe_url)" ] || {
		uci -q add_list campass.global.probe_url='https://www.baidu.com'
		uci -q add_list campass.global.probe_url='https://www.qq.com'
		uci commit campass
	}
	/etc/init.d/campass enable
	/etc/init.d/rpcd reload 2>/dev/null
	rm -f /tmp/luci-indexcache* 2>/dev/null
	rm -rf /tmp/luci-modulecache 2>/dev/null
	# start 会注册 procd 触发器; enabled=0 时不真正拉起 daemon
	/etc/init.d/campass start 2>/dev/null
}
exit 0
